### ISSUE TITLE
Not working with latest Woocommerce

### ISSUE THREAD

**Issue by yratof** [8manos/wc-variations-radio-buttons#1]
This doesn't show anything out of the box with a fresh install of woocommerce and the default theme. I presume something have changed with woocommerce

**Comment by Mantish** [comment]
Hi @yratof 
What version of WordPress and WooCommerce are you using?
The default theme you're using is Twenty Fifteen?

**Comment by yratof** [comment]
Wait a second... Woocoomerce has changed a few things – if you don't have a
price set for the variation, you can't choose a default variation, causing
the list to not show – I don't think it's you, it's classic woo commerce
"not breaking things"

**Comment by Mantish** [comment]
ok, i'll close this then
