### ISSUE TITLE
Some variations remain continually disabled and never get enabled

### ISSUE THREAD

**Issue by stevetronix** [8manos/wc-variations-radio-buttons#11]
<img width="346" alt="screen shot 2016-03-29 at 2 40 49 pm" src="https://cloud.githubusercontent.com/assets/496718/14119284/75cdabbe-f5bb-11e5-8537-d7533c575861.png">

The Eau de Toilette Rechargeable Spray only comes in the size 75ml. This variation cannot be selected, it remains disabled. If I choose "Eau de Toilette" or "Eau de Parfum", I can only select sizes of 50ml or 100ml. And if I select sizes of 50ml or 100ml, I can only select "Eau de Toilette" or "Eau de Parfum". It becomes an endless loop of a disabled variation.

**Comment by Mantish** [comment]
Hi @stevetronix 
That's a drawback of using variations. If there's a variation that doesn't share at least one attribute with the other variations, there's no easy way to select it. That's what the **clear** button is for.
Another option is to split your product into two.
