### ISSUE TITLE
Different view on calling WC action

### ISSUE THREAD

**Issue by tmconnect** [8manos/wc-variations-radio-buttons#12]
On the single product page everything works as expected.

![safari-snapz007](https://cloud.githubusercontent.com/assets/2598781/16003215/d6034f58-315b-11e6-973c-06277ad05979.jpg)

But if I call `do_action( 'woocommerce_single_product_summary' )` on a page where I want to show special products, I got the price range on top and the price for the selected variation on the bottom. The bottom price changes while changing the variation.

![safari-snapz008](https://cloud.githubusercontent.com/assets/2598781/16003308/3fcdc7d8-315c-11e6-9566-f47241ad5a16.jpg)

I can't find any reason why this happens. Did you get any idea?

Thanks for help!

**Comment by Mantish** [comment]
Hi @tmconnect 
Is this caused by the plugin?
I mean, how does it look when the plugin is disabled?

**Comment by tmconnect** [comment]
Oh sorry, if the plugin is disabled and the WC variable.php is called I got the price range on and the selected price on the bottom as well.

But it's strange: The single product page is generated with the content-single-product.php where the function `woocommerce_single_product_summary` is called. But the result is different????

In the meantime I build a jQuery solution that puts the selected price below the title and hides the price range.

Thanks
Thomas
