### ISSUE TITLE
add compatibility with WooCommerce 3.0

### ISSUE THREAD

**Issue by gregsullivan** [8manos/wc-variations-radio-buttons#24]
When changing the attribute via the radio buttons, the appropriate variation image is no longer loaded.

**Comment by gregsullivan** [comment]
Just as an update to my initial note, I've been able to get this working by using the add-to-cart-variation.js supplied with latest WooCommerce and making changes to support radio buttons.

Has anyone else experienced this issue? I'm not using many plugins on the site in questions, but I'm open to being told it's something specific to my setup.

**Comment by Mantish** [comment]
Hi, WC 3.0 is a major version so it's very likely that we need to update the plugin.
@gregsullivan would you like to make a pull request?

**Comment by gregsullivan** [comment]
Makes sense! The work I did was very specific to the client needs I had for the plugin, so I actually ended up disabling some unneeded functionality from the WooCommerce JavaScript file rather than switch it over to working with radio buttons.

I'd be happy to post what I have so far, with the caveat that it's incomplete for general purpose use.
