### ISSUE TITLE
HOW TO ADD checkbox BUTTONS TO WOOCOMMERCE VARIATIONS?

### ISSUE THREAD

**Issue by hmbashar** [8manos/wc-variations-radio-buttons#29]
HOW TO ADD checkbox BUTTONS TO WOOCOMMERCE VARIATIONS? please help me, i want to change select menu to checkbox with individual price. on single item page and shop page, like https://prnt.sc/hh6yn7

**Comment by Mantish** [comment]
You can ask for help here https://wordpress.org/plugins/wc-variations-radio-buttons/
Also, yelling is not nice
