### ISSUE TITLE
Product dimensions are not displayed correctly

### ISSUE THREAD

**Issue by mathis89** [8manos/wc-variations-radio-buttons#31]
I noticed that the product dimensions after the last woocommerce update were no longer displayed correctly. After looking for the error, I changed the line 207 in the add-to-cart-variation.js file as follows:

old: $dimensions.wc_set_content (variation.dimensions);
new: $dimensions.wc_set_content (variation.dimensions_html);

It would be great if this is considered for the next plugin update.

**Comment by Mantish** [comment]
thanks for reporting. what version of woocommerce is that?
