### ISSUE TITLE
More than one add-to-cart forms on one page issue

### ISSUE THREAD

**Issue by enventa** [8manos/wc-variations-radio-buttons#33]
Hi there!

great plugin! I have been using it for a while on several websites. Now I'm facing an issue when a product page has more than one "form.cart". I know it is not a usual thing to have more than one form on the same page, but let's imagine it is a very long page, so my client wants to have more than one "add-to-cart" form on the product page (I cannot provide a link because I'm developing locally).

The issue is that when selecting one option from one of the add-to-cart forms, the value only changes on the first form of the page, not on the one used or on all of them. My guess is that it is because you use "id" attribute. Could you consider to use "class" or any other way so that there can be more than one add-to-cart forms on the same page? Any fix I can use right away?

Thanks!

**Comment by enventa** [comment]
Silly me! It is as easy as changing the input id every time a new "add-to-cart" block is rendered... unless you have a better way, of course.

**Comment by Mantish** [comment]
Hi, that's a very specific functionality. I'm glad you found a way to do it!
I'm closing the issue
