### ISSUE TITLE
Update to template - conflict with WC 3.4

### ISSUE THREAD

**Issue by joshrives** [8manos/wc-variations-radio-buttons#36]
I ran into an issue where I had some custom inputs added and this plugin was causing them to show twice. I was able to fix this by removing `do_action( 'woocommerce_before_add_to_cart_button' );` from variable.php in the template folder. This line is no longer in the Woocommerce version of the template file either. Hope this helps someone.

**Comment by Mantish** [comment]
Thanks for reporting @joshrives! 
Would you like to contribute with a pull request?

**Comment by Mantish** [comment]
fixed with b25d9a4649393dce626ed6cc9b28539dfa0f785e
