### ISSUE TITLE
Update to latest versions of WP and WC

### ISSUE THREAD

**Issue by Mantish** [8manos/wc-variations-radio-buttons#39]

**Comment by koppor** [comment]
I have WooCommerce 4.2.2 running and the plugin runs like a charm (only a basic shop).

However, it reports somehow that it is tested only up to version 3.5.

![grafik](https://user-images.githubusercontent.com/1366654/86960814-60023500-c160-11ea-9eff-a5a45183903e.png)

**Comment by Mantish** [comment]
fixed here: 44acaeee3d6e2ce3d9efef36e458b9cdd2eed852
