### ISSUE TITLE
Invalid value posted for Configuration

### ISSUE THREAD

**Issue by graffxdesign** [8manos/wc-variations-radio-buttons#40]
Hello,

I am getting 'Invalid value posted for Configuration' when I try to add products to the cart. I have 3 variables and when I have the module off it works, and when it is on I get 'Invalid value posted for Configuration' when I try to add products to the cart.

Thank you :)

**Comment by Mantish** [comment]
Hi, can you give us a bit a few more details:
- version of WP and WC you're using
- what theme are you using?

Is you're site online so we can check it out?
Have you tried using a different theme or testing it with other plugins turned off?
