### ISSUE TITLE
Is plugin abandoned? Can we take over the development of it?

### ISSUE THREAD

**Issue by oneteamsoftware** [8manos/wc-variations-radio-buttons#43]
It seems like a nice and very useful plugin. I've looked over issues in wordpress: https://wordpress.org/support/plugin/wc-variations-radio-buttons/ 
and it does not look like many of the reported issues were resolved. I've also noticed that people have suggested to use filters instead of overwriting templates in github with the code snippets that wasn't adapted even after two years.

As I understood you might be fairly busy and might not have enough time to maintain it ,so I was wondering if we can take over it and take this awesome plugin to the next level?
I read that you are offering to submit changes to you, which would have been fine if this project has been actively maintained, but we can write a lot of code and it might be overwhelming to go over every change we will make and it is last the thing any developer wants for the code to never (or very slowly) be merged and available to the customers.

I understand that it is your baby and you might be attached to what you've created, but look at it that there is a good possibility for it to reach new heights, so people can appreciate what you've originally created even more.

I was wondering if we can take over the development and maintenance of this plugin, we promise to listen to your input and we are planing to fix all the reported issues and implement a lot of new useful features.

My email is dmitry at 1teamsoftware.com we also have a contact form https://1teamsoftware.com/contact-us we will be very happy to talk all the details with you.

**Comment by Mantish** [comment]
Hi, I already answered to you in the Wordpress forum.
The plugin is not abandoned.
If you'd like to contribute, there are some open issues you can work on, or you can add any more if you have any ideas
