### ISSUE TITLE
resetting variations button isn’t working

### ISSUE THREAD

**Issue by marian-kadanka** [8manos/wc-variations-radio-buttons#45]
At least since upgrade to WordPress 5.6, hence jQuery 3.5.1, resetting variations button (link) isn't working anymore. Changing .removeAttr( "checked" ) to .prop( "checked", false) fixes the issue.

More info: https://www.drupal.org/project/simpleads/issues/2417463

Attaching pull request #44

**Comment by Mantish** [comment]
just fixed by #44
