### ISSUE TITLE
Add support for Woocommerce Ajax add to cart variable products

### ISSUE THREAD

**Issue by Mantish** [8manos/wc-variations-radio-buttons#5]
https://wordpress.org/plugins/woocommerce-ajax-add-to-cart-for-variable-products/

**Comment by uaprom** [comment]
Super, is already working ???

**Comment by Mantish** [comment]
not yet, pull requests are welcomed

**Comment by Mantish** [comment]
I think this should be done in the Ajax add to cart variable plugin

**Comment by Mantish** [comment]
support was added in the latest version (1.2.5) of Woocommerce Ajax add to cart for variable products
