### ISSUE TITLE
Allow users to select more than one radio button

### ISSUE THREAD

**Issue by weareevisar** [8manos/wc-variations-radio-buttons#6]
Hi,

Is it possible for users to select more than one radio button? If I have 20 product variations I'd like it so that users can tick all that apply to help build up a bespoke product.

Thanks in advance.

**Comment by Mantish** [comment]
Hi,
If you mean selecting more than one option of an attribute, that's not possible. This works just like a select dropdown in that regard.

I suggest you read this https://docs.woothemes.com/document/variable-product/ to setup your product attributes / variations

**Comment by weareevisar** [comment]
Thank you!
