### ISSUE TITLE
Can't clear the selection

### ISSUE THREAD

**Issue by Sphinxxxx** [8manos/wc-variations-radio-buttons#9]
"Clear"ing the selection doesn't work, because it triggers a bug in the JS code.
![tmpb5e4 tmp](https://cloud.githubusercontent.com/assets/7805101/12864558/4d65e808-cc8f-11e5-8182-c178eb2e8925.png)

It's simple, you just need to add the "event" variable that the click handler uses to the handler's argument list:

    .on( 'click', '.reset_variations', function( /*** ---> ***/ event /*** <--- ***/ ) {
        event.preventDefault();
        ...

**Comment by Mantish** [comment]
thanks for the heads-up @Sphinxxxx
